name: optimize images
on: pull_request
jobs:
  optimize:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: compress
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}